name: Test and Release

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '**/*.gitignore'
      - '**/*.eslintrc.json'
      - '**/*.dockerignore'
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    # runs-on: [self-hosted, ubuntu]
    runs-on: ubuntu-latest
    env:
      BUILD_BRANCH: '${{ github.ref_name }}'
      GITHUB_TOKEN: '${{ secrets.GIT_TOKEN }}'
      GIT_USER: '${{ secrets.GIT_USER }}'
      REPO_FULL_NAME: '${{ github.repository }}'
    steps:
      - name: Clone project
        run: |
          REPO_NAME=${REPO_FULL_NAME#*/}
          cd ..
          rm -rf ${REPO_NAME}
          git clone -b ${BUILD_BRANCH} https://${GIT_USER}:${GITHUB_TOKEN}@github.com/${REPO_FULL_NAME}.git

      - name: Remove Swift
        run: |
          rm -rf /root/action-setup-swift-workspace

      - name: Setup Swift
        uses: YOCKOW/Action-setup-swift@v1
        continue-on-error: true
        with:
          swift-version: '5.7'

      - name: Build
        run: swift build
      - name: Tests
        run: swift test

  release:
    name: Release
    if: ${{ success() }}
    # runs-on: [self-hosted, ubuntu]
    runs-on: ubuntu-latest
    needs: [tests]
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          use_github_release_notes: true
          release_name: "Release <RELEASE_VERSION>"
          max_commits: 100